apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todolist
    version: "1.0"
  name: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: ibrahimbdj/todolist:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todolist
  name: todolist
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: todolist
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passwdgeneration
    version: "1.0"
  name: passwdgeneration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwdgeneration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: passwdgeneration
    spec:
      containers:
        - name: passwdgeneration
          image: ibrahimbdj/passwdgeneration:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: passwdgeneration
  name: passwdgeneration
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: passwdgeneration
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: projetmicroservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"


---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todolist
spec:
  hosts:
    - "*"
  gateways:
    - projetmicroservice-gateway
  http:
    - match:
        - uri:
            prefix: /todolist/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: todolist.default.svc.cluster.local

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: passwdgeneration
spec:
  hosts:
    - "*"
  gateways:
    - projetmicroservice-gateway
  http:
    - match:
        - uri:
            prefix: /passwdgeneration/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: passwdgeneration.default.svc.cluster.local